[build]
  base = "client/"
  publish = "build/"
  command = "npm install && npm run build"

[build.environment]
  CI = "false"
  ESLINT_NO_DEV_ERRORS = "true"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200